# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2025-2026 Gord Tulloch

"""TYPE_CHECKING-only shared interface for the app_window mixins.

Each mixin in this package (``_core.py``, ``_imaging_page.py``, ...) is its
own standalone class at runtime, combined into one ``AppWindow`` only in
``__init__.py``. Checked on its own, mypy has no way to know a method in one
mixin will end up sharing ``self`` with the attributes and methods every
*other* mixin defines -- exactly the attribute/method visibility every method
already had for free when this was still one single ~8,000-line class. This
Protocol re-declares that full combined surface (every ``self.`` attribute
and method any mixin uses) purely for mypy: each mixin conditionally
inherits it under ``TYPE_CHECKING`` only (see the ``_MixinBase`` pattern at
the top of every other file in this package), so there is no runtime base
class change, no behavior change, and no import cycle (this module imports
nothing from the mixins). Keep it in sync when adding/removing/renaming a
``self.`` attribute or a mixin method -- a stale entry here just means mypy
stops catching a real typo in that name, the same blind spot the original
single-class file already had for names it never used consistently.

Regenerate with scripts/../gen_state.py (ad hoc, not shipped) after editing
a mixin's attributes or method signatures, rather than hand-editing this file.
"""

from __future__ import annotations

from typing import TYPE_CHECKING, Any, Protocol

from ._common import QPlainTextEdit, QWidget

if TYPE_CHECKING:
    # Only to resolve 3 pre-existing bare-name annotations carried over from
    # the original file (CODE_REVIEW.md Finding 9 cited these as real,
    # unrelated-to-the-split bugs: the mixins that use them still don't
    # import them, same as before -- only fixed here so this stub itself
    # doesn't ALSO report "Name not defined", on top of the original site.
    from galileo.planning.sky_atlas import DeepSkyObject, SkyAtlas
    from galileo.scheduler import ObservatoryScheduler
    from ._threads import (
        _FilterMoveThread,
        _MountPositionThread,
        _ResumeTrackingThread,
        _ThumbnailCacheThread,
    )


class AppWindowState(Protocol):
    # --- attributes -----------------------------------------------------
    _active_camera_slot: str
    _active_optics_position: int
    _camera_backends: Any
    _camera_combo: Any
    _camera_label: Any
    _current_object_label: Any
    _current_observatory: Any
    _current_pier: Any
    _current_primary_section: Any
    _device_pages: Any
    _focus_settings_refresh: Any
    _horizon_table_refresh: Any
    _imaging_capture_thread: Any
    _imaging_debayer_check: Any
    _imaging_filter_combo: Any
    _imaging_filter_thread: _FilterMoveThread | None
    _imaging_preview_renders: Any
    _imaging_service: Any
    _imaging_ui: Any
    _library_screens: Any
    _log_panes: Any
    _nav_columns: Any
    _observatories: Any
    _observatory_combo: Any
    _optics_combo: Any
    _optics_label: Any
    _options_page: Any
    _pier_combo: Any
    _pier_label: Any
    _pier_pointing: Any
    _pier_poll_thread: _MountPositionThread | None
    _primary_nav: Any
    _schedulers: Any
    _sky_atlas: SkyAtlas | None
    _solve_settings_refresh: Any
    _star_atlas_refresh_markers: Any
    _star_atlas_refresh_site: Any
    _star_atlas_set_horizon: Any
    _theme: Any
    _thumbnail_cache_worker: _ThumbnailCacheThread | None
    _tracking_thread: _ResumeTrackingThread | None
    _window: Any

    # --- methods --------------------------------------------------------
    # _camera_page.py
    def _build_camera_page(self) -> QWidget: ...

    # _core.py
    def __init__(self) -> None: ...
    def show(self) -> None: ...
    def _build_top_bar(self) -> QWidget: ...
    def _build_primary_nav(self) -> Any: ...
    def _request_quit(self) -> None: ...
    def _toggle_theme(self) -> None: ...
    def _open_manual(self) -> None: ...
    def _show_about(self) -> None: ...
    def _build_submenu_page(self, items: list, builders: dict) -> QWidget: ...
    def _build_placeholder_page(self, title: str) -> QWidget: ...

    # _current_object.py
    def current_object(self) -> Any: ...
    def _set_current_object(self, atlas_obj: dict) -> None: ...
    def _add_to_session(self, name: str, ra_deg: float, dec_deg: float) -> None: ...
    def _shared_sky_atlas(self) -> SkyAtlas: ...
    def _select_result(self, obj: DeepSkyObject) -> None: ...
    def _show_full_image(self, obj: DeepSkyObject) -> None: ...
    def _refresh_current_object(self) -> None: ...

    # _device_config_page.py
    def _build_device_config_page(self, cat_id: str, label: str) -> QWidget: ...
    def _load_device_config_into_page(self, cat_id: str, state: dict) -> None: ...
    def _save_device_config(self, cat_id: str, state: dict) -> None: ...

    # _filter_wheel_page.py
    def _build_filter_wheel_page(self) -> QWidget: ...

    # _focuser_page.py
    def _build_focuser_page(self) -> QWidget: ...

    # _framing.py
    def _imaging_optical_profile(self) -> dict: ...
    def _framing_dialog_initial_target(self) -> tuple[str, float, float] | None: ...
    def _open_framing_dialog(self, service: Any) -> None: ...

    # _imaging_page.py
    def _build_imaging_page(self) -> QWidget: ...

    # _imaging_support.py
    def camera_not_connected_message(self) -> str: ...
    def _imaging_frame_context(self) -> dict: ...
    def _mount_to_object(self, action: str, obj: dict) -> bool: ...
    def _connect_device_adapter(self, category: Any, driver: str, server: str, port: int, device_name: str) -> Any: ...
    @staticmethod
    def _make_adapter(category: Any, driver: str, server: str, port: int, device_name: str) -> Any: ...
    def _lookup_driver_info(self, category: Any, driver: str, server: str, port: int, device_name: str) -> dict: ...
    @staticmethod
    def _build_driver_info_row() -> tuple: ...
    def _connect_camera_device(self, slot_label: str, driver: str, server: str, port: int, device_name: str) -> None: ...

    # _library_equipment.py
    def _build_library_page(self) -> QWidget: ...
    def _build_library_settings_page(self) -> QWidget: ...
    def _open_library_settings(self) -> None: ...
    def _build_equipment_page(self) -> QWidget: ...
    def _build_log_pane(self) -> QPlainTextEdit: ...
    def _refresh_log_panes(self) -> None: ...
    @staticmethod
    def set_log_pane_text(pane: QPlainTextEdit, text: str) -> None: ...

    # _misc_device_pages.py
    def _build_guider_page(self) -> QWidget: ...
    def _build_focus_page(self) -> QWidget: ...
    def _scheduler_for_pier(self, pier_name: str | None) -> ObservatoryScheduler: ...
    def _build_sessions_page(self) -> QWidget: ...
    def _build_scheduler_page(self) -> QWidget: ...
    def _build_solve_page(self) -> QWidget: ...

    # _mount_page.py
    def _build_mount_page(self) -> QWidget: ...

    # _observatory_pier.py
    def _load_observatories(self) -> None: ...
    def _prompt_new_name(self, title: str, label_text: str) -> str | None: ...
    def _prompt_new_observatory(self) -> dict | None: ...
    def _on_observatory_activated(self, index: int) -> None: ...
    def _index_of_current_observatory(self, combo: Any) -> int: ...
    def _select_observatory(self, observatory: Any) -> None: ...
    def _refresh_pier_combo(self) -> None: ...
    def _on_pier_activated(self, index: int) -> None: ...
    def _index_of_current_pier(self, combo: Any) -> int: ...
    def _on_pier_changed(self) -> None: ...
    def _log_pier_switch_timings(self, total: float, timings: list[tuple[str, float]]) -> None: ...
    def _apply_horizon(self) -> None: ...
    def pier_markers(self) -> list: ...
    def _poll_pier_pointing(self, on_done: Any = ...) -> None: ...
    def _track_when_slew_finishes(self, mount: Any, target: Any = ...) -> None: ...

    # _optics_page.py
    def _build_optics_page(self) -> QWidget: ...

    # _planning_page.py
    def _build_sky_atlas_page(self) -> QWidget: ...
    def _build_criteria_panel(self, heading: str) -> Any: ...

    # _rotator_page.py
    def _build_rotator_page(self) -> QWidget: ...

    # _settings_pages.py
    def _build_star_atlas_settings_page(self) -> QWidget: ...
    def _build_planning_settings_page(self) -> QWidget: ...
    def _cache_all_catalog_thumbnails(self, parent: QWidget) -> None: ...
    def _build_imaging_settings_page(self) -> QWidget: ...
    def _build_focus_settings_page(self) -> QWidget: ...
    def _build_solve_settings_page(self) -> QWidget: ...

    # _star_atlas_page.py
    def _build_star_atlas_page(self) -> QWidget: ...

    # _topbar_optics_camera.py
    def _refresh_optics_combo(self) -> None: ...
    def _on_optics_activated(self, index: int) -> None: ...
    def _active_filter_wheel(self) -> Any: ...
    def _refresh_imaging_filters(self) -> None: ...
    def _on_imaging_filter_activated(self, _index: int = ...) -> None: ...
    def active_optical_tube(self) -> Any: ...
    def _refresh_camera_combo(self) -> None: ...
    def _on_camera_activated(self, index: int) -> None: ...

